secret_devise: 'CHANGEXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
secret_token: 'CHANGEXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
secret_key_base: 'CHANGEXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'

opensuse_connect_api_key: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
